import Head from "next/head";
import Link from "next/link";
import MyAppBar from "../components/MyAppBar";
import { Container, CssBaseline, Grid, ThemeProvider } from "@mui/material";
import { lightTheme, darkTheme } from "@/styles/mui/theme";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getActiveTheme, selectTheme } from "@/redux/reducers/themeReducer";


export default function Home() {
  
  const dispatch = useDispatch(); // Hook to access the Redux dispatch function

  const currentTheme = useSelector(selectTheme).activeTheme; // Access the current theme from the Redux store

  useEffect(() => {
    dispatch(getActiveTheme); // to get theme from cookie
  })
  
  return (
    <>
    <ThemeProvider theme={currentTheme === "light" ? lightTheme : darkTheme}>
      <CssBaseline />
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppBar />
      <Container>
        <Grid justifyContent="center">
        
        <h1>Contact Us</h1>
        <p>Name: Shawn Bruno<br />Email: sb@example.com<br />Address: Assam Don Bosco University, Azara Campus </p>
        <br />
        <Link href="/dashboard">Dashboard</Link>
        </Grid>
      </Container>
    </ThemeProvider>
    </>
  );
}
