import Head from "next/head";
import Link from "next/link";
import MyAppBar from "../components/MyAppBar";
import { Container, Grid, ThemeProvider } from "@mui/material";
import { lightTheme, darkTheme } from "@/styles/mui/theme";


export default function Home() {
  return (
    <>
    <ThemeProvider theme={lightTheme}>
      <Head>
        <title>SovaMeet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppBar />
      <Container>
        <Grid justifyContent="center">
        
        <h1>Contact Us</h1>
        <p>Name: Shawn Bruno<br />Email: sb@example.com<br />Address: Assam Don Bosco University, Azara Campus </p>
        <br />
        <Link href="/dashboard">Dashboard</Link>
        </Grid>
      </Container>
    </ThemeProvider>
    </>
  );
}
