import Head from "next/head";
import Link from "next/link";
import MyAppBar from "../components/MyAppBar";
import { Container, Grid } from "@mui/material";
import { Box, ThemeProvider } from "@mui/material";
import { CustomCard } from "@/styles/mui/customComponents";
import { lightTheme, darkTheme } from "@/styles/mui/theme";

export default function Home() {
  return (
    <>
    <ThemeProvider theme={lightTheme}>
      <Head>
        <title>SovaMeet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppBar /><br />
      <Container>
        <Grid justifyContent="center">
        <h1>SovaMeet</h1>
        <p>Welcome to SovaMeet! <br />Video Conference with AI power ASL Translation</p>
        <br />
        <Link href="/dashboard">Dashboard</Link>
        </Grid>
      </Container>
    </ThemeProvider>
    </>
  );
}
